version: '3'

services:

  myapp:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules/
    container_name: Test-Server
    ports:
      - "4000:4000"
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./data/redis:/data/redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]